import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import StoreProvider from "@/lib/store/StoreProvider";

// import Navbar from "@/components/header/Navbar";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/sonner";

// import dynamic from "next/dynamic";

// const ThemeProviderClient = dynamic(() =>
//   import("@/components/theme-provider").then((mod) => mod.ThemeProvider)
// );

import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"],
  display: "swap",
  style: ["normal", "italic"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Online Courses",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} font-sans  dark:bg-background`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader color="#7c3aed" showSpinner={false} />
          <StoreProvider>
            {/* <Header /> */}
            <main>{children}</main>
          </StoreProvider>
          <Toaster richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
